name = "checklist-test"
status = "something-else"
description = "Test"
created_at = "2026-05-19T11:31:42.006688Z"
updated_at = "2026-06-26T07:22:30.361189Z"
tags = []

[[checklist]]
text = "Step one"
checked = true

[[checklist]]
text = "Step two"
checked = false

[[checklist]]
text = "more"
checked = false

[[checklist]]
text = "even more"
checked = false
